# Generated by Django 5.0.7 on 2024-07-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='postal_code',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
